/** Nice Books 书封展示配置：不污染 Book 领域模型。 */
export type CoverFamily = "literary" | "history" | "science" | "essay";

/** 每本书的固定封面族；未知 ID 由 coverFamilyForId() 退回文学族。 */
export const COVER_FAMILY_BY_ID: Readonly<Record<string, CoverFamily>> = {
	"01": "literary",
	"02": "literary",
	"03": "science",
	"04": "literary",
	"05": "essay",
	"06": "history",
	"07": "literary",
	"08": "essay",
	"09": "essay",
	"10": "literary",
	"11": "literary",
	"12": "literary",
	"13": "essay",
	"14": "history",
	"15": "history",
	"16": "history",
	"17": "science",
	"18": "literary",
	"19": "science",
	"20": "literary",
	"21": "history",
	"22": "essay",
	"23": "literary",
	"24": "literary",
	"25": "history",
	"26": "history",
	"27": "essay",
	"28": "literary",
	"29": "literary",
	"30": "literary",
	"31": "literary",
	"32": "literary",
	"33": "essay",
	"34": "literary",
	"35": "literary",
	"36": "literary",
	"37": "literary",
	"38": "essay",
	"39": "literary",
	"40": "literary",
	"41": "essay",
	"42": "essay",
	"43": "essay",
	"44": "history",
	"45": "history",
	"46": "literary",
	"47": "literary",
	"48": "literary",
	"49": "literary",
	"50": "literary",
	"51": "literary",
	"52": "literary",
	"53": "literary",
	"54": "literary",
	"55": "literary",
	"56": "literary",
	"57": "literary",
	"58": "literary",
	"59": "literary",
	"60": "literary",
	"61": "science",
	"62": "literary",
	"63": "literary",
	"64": "science",
	"65": "science",
	"66": "science",
	"67": "history",
	"68": "history",
	"69": "science",
	"70": "essay",
};

export function coverFamilyForId(id: string): CoverFamily {
	return COVER_FAMILY_BY_ID[id] ?? "literary";
}
